### ISSUE TITLE
Groups do not appear to be selected - GLPI 9.5.2

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/itilcategorygroups#36]
Hello!

After installing the plugin, I am not able to select the groups to filter in version 9.5.2

List of categories on the entitie
![image](https://user-images.githubusercontent.com/35368369/98884156-32aaf800-246e-11eb-90e1-8d5a7e9f9265.png)

![image](https://user-images.githubusercontent.com/35368369/98884216-553d1100-246e-11eb-827f-11dbb2c7b718.png)

![image](https://user-images.githubusercontent.com/35368369/98884676-4dca3780-246f-11eb-968f-ab3e6c5c0714.png)

Plugin dont access groups

![image](https://user-images.githubusercontent.com/35368369/98884715-620e3480-246f-11eb-8781-5cb9fca1ff8c.png)

**Comment by cedric-anne** [comment]
Hi,

Can you check your GLPI logs to see if there is an error trace corresponding to this issue?

Regards

**Comment by mecmav** [comment]
I have the same issue in glpi 9.5.3.
Already set group, but don't shown as expected at screen to assign

**Comment by bacus99** [comment]
Same for me

**Comment by phamorais** [comment]
@cedric-anne 
Hello guys, the idea of ​​this plugin is very good. Will it still be continued? Has the mentioned error been verified?

**Comment by orthagh** [comment]
Hello all.

I just added a commit in develop branch to fix this issue.
This is due to extra security added in GLPI 9.5.2 (to avoid data breach).

Just pick the patch and apply it on your plugin: https://github.com/pluginsGLPI/itilcategorygroups/commit/0ed35c132e63dc8db28d5b4ff5636545faa28b72.patch

Or wait for a new release 

You can also disable the idor security in GLPI to temporary fix this issue by creating a `config/local_define.php` in glpi root containing:
```php
<?php

define('GLPI_USE_IDOR_CHECK', false);

```

(Please don't do that on critical instances, you reduce security)
